<?php

namespace garethp\ews\API\Message;

use garethp\ews\API\Message;

/**
 * Class representing ResponseMessageType
 *
 *
 * XSD Type: ResponseMessageType
 */
class ResponseMessageType extends Message
{

    /**
     * @var string
     */
    protected $responseClass = null;

    /**
     * @var string
     */
    protected $messageText = null;

    /**
     * @var string
     */
    protected $responseCode = null;

    /**
     * @var integer
     */
    protected $descriptiveLinkKey = null;

    /**
     * @var \garethp\ews\API\Message\ResponseMessageType\MessageXmlAType
     */
    protected $messageXml = null;

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getResponseClass()
    {
        return $this->responseClass;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ResponseMessageType
     */
    public function setResponseClass($value)
    {
        $this->responseClass = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getMessageText()
    {
        return $this->messageText;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ResponseMessageType
     */
    public function setMessageText($value)
    {
        $this->messageText = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return string
     */
    public function getResponseCode()
    {
        return $this->responseCode;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value string
     * @return ResponseMessageType
     */
    public function setResponseCode($value)
    {
        $this->responseCode = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return integer
     */
    public function getDescriptiveLinkKey()
    {
        return $this->descriptiveLinkKey;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value int
     * @return ResponseMessageType
     */
    public function setDescriptiveLinkKey($value)
    {
        $this->descriptiveLinkKey = $value;
        return $this;
    }

    /**
     * @autogenerated This method is safe to replace
     * @return \garethp\ews\API\Message\ResponseMessageType\MessageXmlAType
     */
    public function getMessageXml()
    {
        return $this->messageXml;
    }

    /**
     * @autogenerated This method is safe to replace
     * @param $value \garethp\ews\API\Message\ResponseMessageType\MessageXmlAType
     * @return ResponseMessageType
     */
    public function setMessageXml($value)
    {
        if (is_array($value) || $value instanceof \stdClass) {
            $extra = json_encode($value, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
            if ($extra) {
                $this->messageText = trim(($this->messageText ?? '') . "\n" . $extra);
            }

            $this->messageXml = null;
            return $this;
        }

        $this->messageXml = $value;
        return $this;
    }
}
